gui:
  nerdFontsVersion: "3"
  showFileTree: false
  skipRewordInEditorWarning: true
git:
  branchLogCmd: "git log --pretty=format:\"%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)\" --graph --date=relative --decorate {{branchName}} --"
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --color-only --paging=never
  allBranchesLogCmds:
    - git log --pretty=format:"%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)" --graph --date=relative --decorate --all
customCommands:
  - key: "c"
    context: "commits"
    description: "yank commit hash"
    command: "git rev-parse HEAD | pbcopy"
  - key: "n"
    context: "files"
    description: "git now"
    command: "git now"
